[package]
name = "nocap-crypt-keymgmt"
version.workspace = true
edition.workspace = true
license-file.workspace = true

[dependencies]
nocap-crypt-core = { workspace = true }
nocap-crypt-entropy = { workspace = true }
thiserror = { workspace = true }
sha2 = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
base64 = { workspace = true }
